/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dashboard: typeof import('./src/components/pages/dashboard.vue')['default']
    Footer: typeof import('./src/components/Footers/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavMain: typeof import('./src/components/Navs/NavMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleTraining: typeof import('./src/components/SingleTraining.vue')['default']
    Todos: typeof import('./src/components/Todos.vue')['default']
  }
}
